### ISSUE TITLE
What should be inserted in JWT_SECRET and PASSWORD when not using Heroku deploy button?

### ISSUE THREAD

**Issue by Nagendra080389** [Stwissel/SpringCanvasSample#2]
When I deploy your app to my heroku via heroku button, it works well. But when I cloned your repository and tried to host it to heroku it fails : "JWT signature does not match locally computed signature. JWT validity cannot be asserted and should not be trusted."

I see that your app has four environment variables, which is prompted when I deploy it with heroku button, So I gave only AdminName and sfdcsecret, as others were showing as auto generated. But when I try to do it, i have to manually put the variables, so adminname and sfdcsecret i have put, but what to put in jwtsecret and password.

This is my app, none of the endpoints are working as launching spring boot fails 

https://sfpagebuilder.herokuapp.com/

`2019-10-12T13:46:42.719317+00:00 app[web.1]: Using generated security password: 7fab5c44-0242-4d00-9f1b-ee943215e386
2019-10-12T13:46:42.719319+00:00 app[web.1]: 
2019-10-12T13:46:42.887344+00:00 app[web.1]: 2019-10-12 13:46:42.887  INFO 4 --- [           main] o.s.s.web.DefaultSecurityFilterChain     : Creating filter chain: any request, [org.springframework.security.web.context.request.async.WebAsyncManagerIntegrationFilter@7d4f9aae, org.springframework.security.web.context.SecurityContextPersistenceFilter@1e1a0406, org.springframework.security.web.header.HeaderWriterFilter@36916eb0, org.springframework.security.web.csrf.CsrfFilter@4dbb42b7, org.springframework.security.web.authentication.logout.LogoutFilter@71a8adcf, com.notessensei.heroku.springcanvassample.security.CanvasAuthorizationFilter@72e5a8e, org.springframework.security.web.savedrequest.RequestCacheAwareFilter@12aba8be, org.springframework.security.web.servletapi.SecurityContextHolderAwareRequestFilter@6253c26, org.springframework.security.web.authentication.AnonymousAuthenticationFilter@54e1c68b, org.springframework.security.web.session.SessionManagementFilter@437da279, org.springframework.security.web.access.ExceptionTranslationFilter@550dbc7a, org.springframework.security.web.access.intercept.FilterSecurityInterceptor@b9b00e0]
2019-10-12T13:46:43.213026+00:00 app[web.1]: 2019-10-12 13:46:43.212  INFO 4 --- [           main] o.s.s.concurrent.ThreadPoolTaskExecutor  : Initializing ExecutorService 'applicationTaskExecutor'
2019-10-12T13:46:43.805646+00:00 app[web.1]: 2019-10-12 13:46:43.805  INFO 4 --- [           main] o.s.b.a.e.web.EndpointLinksResolver      : Exposing 2 endpoint(s) beneath base path '/actuator'
2019-10-12T13:46:43.975858+00:00 app[web.1]: 2019-10-12 13:46:43.975  INFO 4 --- [           main] o.s.b.w.embedded.tomcat.TomcatWebServer  : Tomcat started on port(s): 53501 (http) with context path ''
2019-10-12T13:46:43.982816+00:00 app[web.1]: 2019-10-12 13:46:43.982  INFO 4 --- [           main] c.n.h.s.SfpagebuilderApplication         : Started SfpagebuilderApplication in 9.07 seconds (JVM running for 10.608)
2019-10-12T13:46:44.560143+00:00 heroku[web.1]: State changed from starting to up
2019-10-12T13:46:46.418913+00:00 app[web.1]: 2019-10-12 13:46:46.417  INFO 4 --- [io-53501-exec-3] o.a.c.c.C.[Tomcat].[localhost].[/]       : Initializing Spring DispatcherServlet 'dispatcherServlet'
2019-10-12T13:46:46.418931+00:00 app[web.1]: 2019-10-12 13:46:46.417  INFO 4 --- [io-53501-exec-3] o.s.web.servlet.DispatcherServlet        : Initializing Servlet 'dispatcherServlet'
2019-10-12T13:46:46.42899+00:00 app[web.1]: 2019-10-12 13:46:46.428  INFO 4 --- [io-53501-exec-3] o.s.web.servlet.DispatcherServlet        : Completed initialization in 10 ms
2019-10-12T13:46:46.760465+00:00 app[web.1]: 2019-10-12 13:46:46.759 ERROR 4 --- [io-53501-exec-3] c.n.h.s.s.CanvasAuthorizationFilter      : JWT signature does not match locally computed signature. JWT validity cannot be asserted and should not be trusted.
2019-10-12T13:46:46.760488+00:00 app[web.1]: 
2019-10-12T13:46:46.760491+00:00 app[web.1]: io.jsonwebtoken.SignatureException: JWT signature does not match locally computed signature. JWT validity cannot be asserted and should not be trusted.
2019-10-12T13:46:46.760493+00:00 app[web.1]: 	at io.jsonwebtoken.impl.DefaultJwtParser.parse(DefaultJwtParser.java:354) ~[jjwt-0.9.0.jar!/:0.9.0]
2019-10-12T13:46:46.760495+00:00 app[web.1]: 	at io.jsonwebtoken.impl.DefaultJwtParser.parse(DefaultJwtParser.java:481) ~[jjwt-0.9.0.jar!/:0.9.0]
2019-10-12T13:46:46.760497+00:00 app[web.1]: 	at io.jsonwebtoken.impl.DefaultJwtParser.parseClaimsJws(DefaultJwtParser.java:541) ~[jjwt-0.9.0.jar!/:0.9.0]
2019-10-12T13:46:46.7605+00:00 app[web.1]: 	at com.notessensei.heroku.springcanvassample.security.CanvasAuthorizationFilter.extractAuthentication(CanvasAuthorizationFilter.java:105) [classes!/:0.0.1-SNAPSHOT]
2019-10-12T13:46:46.760502+00:00 app[web.1]: 	at com.notessensei.heroku.springcanvassample.security.CanvasAuthorizationFilter.doFilterInternal(CanvasAuthorizationFilter.java:77) [classes!/:0.0.1-SNAPSHOT]
2019-10-12T13:46:46.760504+00:00 app[web.1]: 	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119) [spring-web-5.1.10.RELEASE.jar!/:5.1.10.RELEASE]
2019-10-12T13:46:46.760507+00:00 app[web.1]: 	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334) [spring-security-web-5.1.6.RELEASE.jar!/:5.1.6.RELEASE]
2019-10-12T13:46:46.760509+00:00 app[web.1]: 	at org.springframework.security.web.authentication.logout.LogoutFilter.doFilter(LogoutFilter.java:116) [spring-security-web-5.1.6.RELEASE.jar!/:5.1.6.RELEASE]
2019-10-12T13:46:46.760511+00:00 app[web.1]: 	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334) [spring-security-web-5.1.6.RELEASE.jar!/:5.1.6.RELEASE]
2019-10-12T13:46:46.760512+00:00 app[web.1]: 	at org.springframework.security.web.csrf.CsrfFilter.doFilterInternal(CsrfFilter.java:100) [spring-security-web-5.1.6.RELEASE.jar!/:5.1.6.RELEASE]
2019-10-12T13:46:46.760514+00:00 app[web.1]: 	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119) [spring-web-5.1.10.RELEASE.jar!/:5.1.10.RELEASE]
2019-10-12T13:46:46.760517+00:00 app[web.1]: 	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334) [spring-security-web-5.1.6.RELEASE.jar!/:5.1.6.RELEASE]
2019-10-12T13:46:46.760519+00:00 app[web.1]: 	at org.springframework.security.web.header.HeaderWriterFilter.doFilterInternal(HeaderWriterFilter.java:74) [spring-security-web-5.1.6.RELEASE.jar!/:5.1.6.RELEASE]
2019-10-12T13:46:46.760521+00:00 app[web.1]: 	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119) [spring-web-5.1.10.RELEASE.jar!/:5.1.10.RELEASE]
2019-10-12T13:46:46.760523+00:00 app[web.1]: 	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334) [spring-security-web-5.1.6.RELEASE.jar!/:5.1.6.RELEASE]
2019-10-12T13:46:46.760525+00:00 app[web.1]: 	at org.springframework.security.web.context.SecurityContextPersistenceFilter.doFilter(SecurityContextPersistenceFilter.java:105) [spring-security-web-5.1.6.RELEASE.jar!/:5.1.6.RELEASE]
2019-10-12T13:46:46.760534+00:00 app[web.1]: 	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334) [spring-security-web-5.1.6.RELEASE.jar!/:5.1.6.RELEASE]
2019-10-12T13:46:46.760538+00:00 app[web.1]: 	at org.springframework.security.web.context.request.async.WebAsyncManagerIntegrationFilter.doFilterInternal(WebAsyncManagerIntegrationFilter.java:56) [spring-security-web-5.1.6.RELEASE.jar!/:5.1.6.RELEASE]
2019-10-12T13:46:46.76054+00:00 app[web.1]: 	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119) [spring-web-5.1.10.RELEASE.jar!/:5.1.10.RELEASE]
2019-10-12T13:46:46.760542+00:00 app[web.1]: 	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334) [spring-security-web-5.1.6.RELEASE.jar!/:5.1.6.RELEASE]
2019-10-12T13:46:46.760545+00:00 app[web.1]: 	at org.springframework.security.web.FilterChainProxy.doFilterInternal(FilterChainProxy.java:215) [spring-security-web-5.1.6.RELEASE.jar!/:5.1.6.RELEASE]
2019-10-12T13:46:46.760547+00:00 app[web.1]: 	at org.springframework.security.web.FilterChainProxy.doFilter(FilterChainProxy.java:178) [spring-security-web-5.1.6.RELEASE.jar!/:5.1.6.RELEASE]
2019-10-12T13:46:46.760549+00:00 app[web.1]: 	at org.springframework.web.filter.DelegatingFilterProxy.invokeDelegate(DelegatingFilterProxy.java:358) [spring-web-5.1.10.RELEASE.jar!/:5.1.10.RELEASE]
2019-10-12T13:46:46.760551+00:00 app[web.1]: 	at org.springframework.web.filter.DelegatingFilterProxy.doFilter(DelegatingFilterProxy.java:271) [spring-web-5.1.10.RELEASE.jar!/:5.1.10.RELEASE]
2019-10-12T13:46:46.76056+00:00 app[web.1]: 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) [tomcat-embed-core-9.0.26.jar!/:9.0.26]
2019-10-12T13:46:46.760562+00:00 app[web.1]: 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) [tomcat-embed-core-9.0.26.jar!/:9.0.26]
2019-10-12T13:46:46.760564+00:00 app[web.1]: 	at org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:100) [spring-web-5.1.10.RELEASE.jar!/:5.1.10.RELEASE]
2019-10-12T13:46:46.760566+00:00 app[web.1]: 	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119) [spring-web-5.1.10.RELEASE.jar!/:5.1.10.RELEASE]
2019-10-12T13:46:46.760568+00:00 app[web.1]: 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) [tomcat-embed-core-9.0.26.jar!/:9.0.26]
2019-10-12T13:46:46.76057+00:00 app[web.1]: 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) [tomcat-embed-core-9.0.26.jar!/:9.0.26]
2019-10-12T13:46:46.760573+00:00 app[web.1]: 	at org.springframework.web.filter.FormContentFilter.doFilterInternal(FormContentFilter.java:93) [spring-web-5.1.10.RELEASE.jar!/:5.1.10.RELEASE]
2019-10-12T13:46:46.760579+00:00 app[web.1]: 	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119) [spring-web-5.1.10.RELEASE.jar!/:5.1.10.RELEASE]
2019-10-12T13:46:46.760581+00:00 app[web.1]: 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) [tomcat-embed-core-9.0.26.jar!/:9.0.26]
2019-10-12T13:46:46.760584+00:00 app[web.1]: 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) [tomcat-embed-core-9.0.26.jar!/:9.0.26]
2019-10-12T13:46:46.760585+00:00 app[web.1]: 	at org.springframework.web.filter.HiddenHttpMethodFilter.doFilterInternal(HiddenHttpMethodFilter.java:94) [spring-web-5.1.10.RELEASE.jar!/:5.1.10.RELEASE]
2019-10-12T13:46:46.760587+00:00 app[web.1]: 	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119) [spring-web-5.1.10.RELEASE.jar!/:5.1.10.RELEASE]
2019-10-12T13:46:46.76059+00:00 app[web.1]: 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) [tomcat-embed-core-9.0.26.jar!/:9.0.26]
2019-10-12T13:46:46.760592+00:00 app[web.1]: 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) [tomcat-embed-core-9.0.26.jar!/:9.0.26]
2019-10-12T13:46:46.760594+00:00 app[web.1]: 	at org.springframework.boot.actuate.metrics.web.servlet.WebMvcMetricsFilter.filterAndRecordMetrics(WebMvcMetricsFilter.java:114) [spring-boot-actuator-2.1.9.RELEASE.jar!/:2.1.9.RELEASE]
2019-10-12T13:46:46.760596+00:00 app[web.1]: 	at org.springframework.boot.actuate.metrics.web.servlet.WebMvcMetricsFilter.doFilterInternal(WebMvcMetricsFilter.java:104) [spring-boot-actuator-2.1.9.RELEASE.jar!/:2.1.9.RELEASE]
2019-10-12T13:46:46.760598+00:00 app[web.1]: 	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119) [spring-web-5.1.10.RELEASE.jar!/:5.1.10.RELEASE]
2019-10-12T13:46:46.7606+00:00 app[web.1]: 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) [tomcat-embed-core-9.0.26.jar!/:9.0.26]
2019-10-12T13:46:46.760602+00:00 app[web.1]: 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) [tomcat-embed-core-9.0.26.jar!/:9.0.26]
2019-10-12T13:46:46.760604+00:00 app[web.1]: 	at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:201) [spring-web-5.1.10.RELEASE.jar!/:5.1.10.RELEASE]
2019-10-12T13:46:46.760606+00:00 app[web.1]: 	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119) [spring-web-5.1.10.RELEASE.jar!/:5.1.10.RELEASE]
2019-10-12T13:46:46.760608+00:00 app[web.1]: 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) [tomcat-embed-core-9.0.26.jar!/:9.0.26]
2019-10-12T13:46:46.760609+00:00 app[web.1]: 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) [tomcat-embed-core-9.0.26.jar!/:9.0.26]
2019-10-12T13:46:46.760612+00:00 app[web.1]: 	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:202) [tomcat-embed-core-9.0.26.jar!/:9.0.26]
2019-10-12T13:46:46.760614+00:00 app[web.1]: 	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96) [tomcat-embed-core-9.0.26.jar!/:9.0.26]
2019-10-12T13:46:46.760616+00:00 app[web.1]: 	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:526) [tomcat-embed-core-9.0.26.jar!/:9.0.26]
2019-10-12T13:46:46.760618+00:00 app[web.1]: 	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:139) [tomcat-embed-core-9.0.26.jar!/:9.0.26]
2019-10-12T13:46:46.76062+00:00 app[web.1]: 	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92) [tomcat-embed-core-9.0.26.jar!/:9.0.26]
2019-10-12T13:46:46.760626+00:00 app[web.1]: 	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:74) [tomcat-embed-core-9.0.26.jar!/:9.0.26]
2019-10-12T13:46:46.760628+00:00 app[web.1]: 	at org.apache.catalina.valves.RemoteIpValve.invoke(RemoteIpValve.java:747) [tomcat-embed-core-9.0.26.jar!/:9.0.26]
2019-10-12T13:46:46.76063+00:00 app[web.1]: 	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343) [tomcat-embed-core-9.0.26.jar!/:9.0.26]
2019-10-12T13:46:46.760633+00:00 app[web.1]: 	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:408) [tomcat-embed-core-9.0.26.jar!/:9.0.26]
2019-10-12T13:46:46.760635+00:00 app[web.1]: 	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66) [tomcat-embed-core-9.0.26.jar!/:9.0.26]
2019-10-12T13:46:46.760637+00:00 app[web.1]: 	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:860) [tomcat-embed-core-9.0.26.jar!/:9.0.26]
2019-10-12T13:46:46.760639+00:00 app[web.1]: 	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1589) [tomcat-embed-core-9.0.26.jar!/:9.0.26]
2019-10-12T13:46:46.76064+00:00 app[web.1]: 	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49) [tomcat-embed-core-9.0.26.jar!/:9.0.26]
2019-10-12T13:46:46.760642+00:00 app[web.1]: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [na:1.8.0_222-heroku]
2019-10-12T13:46:46.760644+00:00 app[web.1]: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [na:1.8.0_222-heroku]
2019-10-12T13:46:46.760646+00:00 app[web.1]: 	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61) [tomcat-embed-core-9.0.26.jar!/:9.0.26]
2019-10-12T13:46:46.760649+00:00 app[web.1]: 	at java.lang.Thread.run(Thread.java:748) [na:1.8.0_222-heroku]
2019-10-12T13:46:46.760651+00:00 app[web.1]: 
2019-10-12T13:46:47.078479+00:00 heroku[router]: at=info method=GET path="/" host=sfpagebuilder.herokuapp.com request_id=da5ba9ca-ac01-4213-b7b7-f93c2bddfb80 fwd="106.51.106.65" dyno=web.1 connect=1ms service=711ms status=404 bytes=771 protocol=https`

**Comment by Stwissel** [comment]
The values need to match what you configured in SFDC. The Admin user/password is to have an access to the app from outside of SFDC. When you check the environment parameters you can see that

**Comment by Nagendra080389** [comment]
But JWT secret does not gets generated in sfdc. Only sfdcsecret gets generated in sfdc.

**Comment by Nagendra080389** [comment]
Got it, might be some issue in folder structure, but when I used your folder structure it worked. Thanks
